on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: 'list testing before'
        run: ls 

      -uses: action/checkout@v3
      
      - name: 'list testing after'
        run: ls 



